### ISSUE TITLE
Support custom bundlesize.js path

### ISSUE THREAD

**Issue by thoov** [kaliber5/ember-cli-bundlesize#3]
Currently: https://github.com/kaliber5/ember-cli-bundlesize/blob/master/lib/tasks/test.js#L10 does not allow a custom config. It would be nice if this either respected `configPath` or allowed a way to specify the location of bundlesize.js.

**Comment by simonihmig** [comment]
With `configPath` you mean this one, which is used for addons? https://ember-cli.com/extending/#configuring-your-ember-addon-properties

Could you explain the use case for needing a different config path? And btw, do the other common config files (`environment.js`, `targets.js` etc. ) support a different path, and if so by what means?

**Comment by thoov** [comment]
Our use case is that we have a `/config` directory that lives within each project internally that is managed by svn (:-() and so we have to rename the config directory that ember provides to `/ember-config` (which is where environment.js, etc live). So we are unable to place a bundlesize.js file within that config directory. We would need some way to specify a different place for the bundlesize.js config. It would be nice to either specify the this custom path path in ember-cli-build.js or in package.json. 

> With configPath you mean this one, which is used for addons? ember-cli.com/extending/#configuring-your-ember-addon-properties

I was using that more as an example. Sorry if that was confusing.

**Comment by simonihmig** [comment]
Closes by #4
